services:
  socialmedia:
    image: kyzman/socialmedia
    depends_on:
      - postgres
    ports:
      - 80:8001
#    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
#    env_file:
#      - ./.env
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}


  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_USERNAME}

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
